#!/bin/bash

# disable firstboot/oobe prompts
touch "$3"/var/db/.AppleDiagnosticsSetupDone
touch "$3"/var/db/.AppleSetupDone

chmod a+rx "$3"/usr/local/bin/*
chmod -R a+rX "$3"/etc/skel

# silence stupid java-not-installed popups:
rm -rf "$3"/System/Library/Frameworks/JavaVM.framework
